### ISSUE TITLE
1.1.4 breaks TMS_Model_Template::fetchAllKeyed()

### ISSUE THREAD

**Issue by tyteen4a03** [guiltar/TMS#2]
1.1.4 added a $nullPrefix parameter to XenForo_Model::fetchAllKeyed(), which allows you to prefix your result keys. This will trigger this message:
Declaration of TMS_Model_Template::fetchAllKeyed() should be compatible with that of XenForo_Model::fetchAllKeyed()
in the admincp.

**Comment by guiltar** [comment]
Thank you very much!
