### ISSUE TITLE
Question regarding opencart

### ISSUE THREAD

**Issue by moodleboy** [guiltar/TMS#5]
I cannot tell you how sorry I am to use this to contact you, but I had no idea how else to do it.

You posted a bug report on opencart (https://github.com/opencart/opencart/issues/3792) which was immediately shot down as "not a bug" by Daniel.  It is, however, a bug, as you correctly stated.

I went looking for help on the OC forums for some guidance, but all I got was lectures about how you shouldn't edit orders (http://forum.opencart.com/viewtopic.php?f=190&t=158405&p=604466).

You mentioned in your post that you were able to correct this issue.  Do you think you could be so kind as to share what it was you did?  I would be most appreciative.

You can contact me directly at moodlehoster@gmail.com.

Thanks in advance,
Paul

**Comment by cthree** [comment]
Hey

I vaguely remember something like this but that would have been many moons ago. Those guys are assholes, I suggest you switch to using shopify.com and save yourself a lot of headache. 

-- ErikP cthree87@gmail.com

**Comment by guiltar** [comment]
Hi, not problem, I've described there in opencart thread.
